{% set name = "picwriter" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/picwriter-{{ version }}.tar.gz
  sha256: 3a92c5e6414b99add5c4d5b3a833b2b2d88f1fa07c3673f7e06b3634270c100f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - gdspy
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - picwriter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/DerekK88/picwriter
  summary: Mask generation tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joamatab
